CrudTask/Models/ErrorViewModel.cs
using System;

namespace CrudTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudTask/Controllers/EstatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer;
using DataLayer.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Models;
using DataLayer.UnitOfWork;
using DataLayer.ViewModels;

namespace CrudTask.Controllers
{
    public class EstatesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EstatesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Estates
        public async Task<IActionResult> Index()
        {
            var estates = await _unitOfWork.EstateRepository.GetAllEstates();
            return View(estates);
        }


        // GET: Estates/Create
        public IActionResult Create()
        {
            var owners = _unitOfWork.OwnerRepository.GetAllOwners();
            var positions = new List<string> {"شمالی", "جنوبی"};
            ViewBag.OwnerId = new SelectList(owners, "OwnerId", "FullName");
            ViewBag.Position = new SelectList(positions);
            return View();
        }

        // POST: Estates/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OwnerId,Name,Area,Address,Position")]
            EstateViewModel estateViewModel)
        {
            if (ModelState.IsValid)
            {
                var estate = new Estate()
                {
                    OwnerId = estateViewModel.OwnerId,
                    Name = estateViewModel.Name,
                    Area = Convert.ToDouble(estateViewModel.Area),
                    Position = estateViewModel.Position,
                    Address = estateViewModel.Address,
                    //ToDo: Get Current User Id from UserManager Repository. At now we assume that is 2
                    ManipulatorUserId = 2,
                    CreationTime = DateTime.Now.ToString("MM/dd/yyyy HH:mm")
                };
                await _unitOfWork.EstateRepository.InsertEstate(estate);
                await _unitOfWork.Commit();
                return RedirectToAction(nameof(Index));
            }

            var owners = _unitOfWork.OwnerRepository.GetAllOwners();
            var positions = new List<string> {"شمالی", "جنوبی"};
            ViewBag.OwnerId = new SelectList(owners, "OwnerId", "FullName");
            ViewBag.Position = new SelectList(positions);

            return View(estateViewModel);
        }

        // GET: Estates/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var estate = await _unitOfWork.EstateRepository.GetEstateById(id);
            if (estate == null)
            {
                return NotFound();
            }

            var estateViewModel = new EstateViewModel()
            {
                EstateId = estate.EstateId,
                OwnerId = estate.OwnerId,
                Name = estate.Name,
                Area = estate.Area.ToString(),
                Position = estate.Position,
                Address = estate.Address,
                CreationTime = estate.CreationTime
            };
            var owners = _unitOfWork.OwnerRepository.GetAllOwners();
            var positions = new List<string> {"شمالی", "جنوبی"};
            ViewBag.OwnerId = new SelectList(owners, "OwnerId", "FullName", estate.OwnerId);
            ViewBag.Position = new SelectList(positions, estate.Position);

            return View(estateViewModel);
        }

        // POST: Estates/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("EstateId,OwnerId,Name,Area,Address,Position,CreationTime")]
            EstateViewModel estateViewModel)
        {
            if (id != estateViewModel.EstateId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var estate = new Estate()
                    {
                        EstateId = estateViewModel.EstateId,
                        OwnerId = estateViewModel.OwnerId,
                        Name = estateViewModel.Name,
                        Area = Convert.ToDouble(estateViewModel.Area),
                        Position = estateViewModel.Position,
                        Address = estateViewModel.Address,
                        //ToDo: Get Current User Id from UserManager Repository. At now we assume that is 2
                        ManipulatorUserId = 2,
                        CreationTime = estateViewModel.CreationTime,
                        UpdateTime = DateTime.Now.ToString("MM/dd/yyyy HH:mm")
                    };
                    _unitOfWork.EstateRepository.UpdateEstate(estate);
                    await _unitOfWork.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstateExists(estateViewModel.EstateId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var owners = _unitOfWork.OwnerRepository.GetAllOwners();
            var positions = new List<string> {"شمالی", "جنوبی"};
            ViewBag.OwnerId = new SelectList(owners, "OwnerId", "FullName", estateViewModel.OwnerId);
            ViewBag.Position = new SelectList(positions, estateViewModel.Position);
            return View(estateViewModel);
        }

        // GET: Estates/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var estate = await _unitOfWork.EstateRepository.GetEstateById(id);
            if (estate == null)
            {
                return NotFound();
            }

            var estateViewModel = new EstateViewModel()
            {
                EstateId = estate.EstateId,
                OwnerId = estate.OwnerId,
                Name = estate.Name,
                OwnerName = string.Format("{0}  {1}", estate.Owner.Name, estate.Owner.Family),
                PhoneNumber = estate.Owner.PhoneNumber,
                Area = estate.Area.ToString(),
                Address = estate.Address,
                Position = estate.Position
            };

            return View(estateViewModel);
        }

        // POST: Estates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _unitOfWork.EstateRepository.DeleteEstate(id);
            await _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));
        }

        // GET: Estates/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var estate = await _unitOfWork.EstateRepository.GetEstateById(id);
            if (estate == null)
            {
                return NotFound();
            }

            var estateViewModel = new EstateViewModel()
            {
                EstateId = estate.EstateId,
                OwnerId = estate.OwnerId,
                Name = estate.Name,
                OwnerName = string.Format("{0}  {1}", estate.Owner.Name, estate.Owner.Family),
                PhoneNumber = estate.Owner.PhoneNumber,
                Area = estate.Area.ToString(),
                Address = estate.Address,
                Position = estate.Position
            };

            return View(estateViewModel);
        }

        private bool EstateExists(int id)
        {
            return _unitOfWork.EstateRepository.IsExist(id);
        }
    }
}

CrudTask/Views/Estates/Create.cshtml
@model DataLayer.ViewModels.EstateViewModel

@{
    ViewData["Title"] = "ایجاد ملک جدید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>ایجاد ملک جدید</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <select asp-for="Position" class="form-control" asp-items="ViewBag.Position"></select>
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت به لیست</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudTask/Views/Estates/Delete.cshtml
@model DataLayer.ViewModels.EstateViewModel

@{
    ViewData["Title"] = "حذف";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5>آیا از حذف ملک مورد نظر مطمئن هستید؟</h5>
<hr/>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EstateId" />
        <input type="submit" value="حذف" class="btn btn-danger" /> |
        <a asp-action="Index">بازگشت به لیست</a>
    </form>
</div>

CrudTask/Views/Estates/Details.cshtml
@model DataLayer.ViewModels.EstateViewModel

@{
    ViewData["Title"] = "جزئیات";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>جزئیات</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EstateId">ویرایش</a> |
    <a asp-action="Index">بازگشت به لیست</a>
</div>

CrudTask/Views/Estates/Edit.cshtml
@model DataLayer.ViewModels.EstateViewModel

@{
    ViewData["Title"] = "ویرایش";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>ویرایش ملک</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EstateId" />
            <input type="hidden" asp-for="CreationTime" />
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <select asp-for="Position" class="form-control" asp-items="ViewBag.Position"></select>
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="به روز رسانی" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت به لیست</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudTask/Views/Estates/Index.cshtml
@model IEnumerable<DataLayer.ViewModels.EstateViewModel>

@{
    ViewData["Title"] = "لیست املاک";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a asp-action="Create">ایجاد ملک جدید</a>
</p>
<table class="table">
    <thead>
        <tr>
         
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.EstateId">ویرایش</a> |
                <a asp-action="Details" asp-route-id="@item.EstateId">جزئیات</a> |
                <a asp-action="Delete" asp-route-id="@item.EstateId">حذف</a>
            </td>
        </tr>
}
    </tbody>
</table>

CrudTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="~/lib/bootstrap/dist/css/bootstrap-rtl.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Estates" asp-action="Index">سامانه ثبت املاک</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>